version: '3.9'
services:
    app:
        image: 'c18f-intern-app'
        build:
            context: .
            dockerfile: ./docker/php-apache/Dockerfile
        ports:
            - '${APP_HOST_PORT}:80'
        volumes:
            - ./src:/var/www
    db:
        image: 'mysql/mysql-server:8.0.28'
        ports:
            - '${DB_HOST_PORT}:3306'
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: 'password'
volumes:
    mysql-store: